package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/xrf9268-hue/aiops-platform/internal/gitea"
	"github.com/xrf9268-hue/aiops-platform/internal/queue"
	"github.com/xrf9268-hue/aiops-platform/internal/runner"
	"github.com/xrf9268-hue/aiops-platform/internal/task"
	"github.com/xrf9268-hue/aiops-platform/internal/workflow"
	"github.com/xrf9268-hue/aiops-platform/internal/workspace"
)

func main() {
	ctx := context.Background()
	dsn := env("DATABASE_URL", "postgres://aiops:aiops@localhost:5432/aiops?sslmode=disable")
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer pool.Close()
	store := queue.New(pool)

	for {
		t, err := store.Claim(ctx)
		if err != nil {
			log.Printf("claim error: %v", err)
			time.Sleep(5 * time.Second)
			continue
		}
		if t == nil {
			time.Sleep(3 * time.Second)
			continue
		}
		if err := runTask(ctx, store, *t); err != nil {
			log.Printf("task %s failed: %v", t.ID, err)
			_ = store.Fail(ctx, t.ID, err.Error())
			continue
		}
		_ = store.Complete(ctx, t.ID)
	}
}

func runTask(ctx context.Context, store *queue.Store, t task.Task) error {
	mgr := workspace.New(env("WORKSPACE_ROOT", "/tmp/aiops-workspaces"))
	workdir, err := mgr.PrepareGitWorkspace(ctx, t)
	if err != nil {
		return err
	}

	wf, err := workflow.LoadOptional(workdir + "/WORKFLOW.md")
	if err != nil {
		return err
	}
	if t.Model == "" || t.Model == "mock" {
		t.Model = wf.Config.Agent.Default
		if t.Model == "" {
			t.Model = "mock"
		}
	}

	prompt := workflow.Render(wf.PromptTemplate, map[string]string{
		"task.id":          t.ID,
		"task.title":       t.Title,
		"task.description": t.Description,
		"task.actor":       t.Actor,
		"repo.owner":       t.RepoOwner,
		"repo.name":        t.RepoName,
		"repo.branch":      t.BaseBranch,
	})
	if err := writeTaskFiles(workdir, t, prompt); err != nil {
		return err
	}

	r, err := runner.New(t.Model)
	if err != nil {
		return err
	}
	if _, err := r.Run(ctx, runner.RunInput{Task: t, Workflow: *wf, Workdir: workdir, Prompt: prompt}); err != nil {
		return err
	}
	if err := workspace.EnforcePolicy(ctx, workdir, wf.Config); err != nil {
		recordPolicyViolation(ctx, store, t.ID, err)
		return err
	}
	if err := workspace.RunVerify(ctx, workdir, wf.Config); err != nil {
		return err
	}
	if err := workspace.CommitAndPush(ctx, workdir, t.Title, t.WorkBranch); err != nil {
		return err
	}
	return createPR(ctx, t, wf.Config)
}

// recordPolicyViolation writes a structured `policy_violation` task event
// before the worker fails the task. The push/PR step is skipped because the
// caller returns the error immediately after this call.
func recordPolicyViolation(ctx context.Context, store *queue.Store, taskID string, err error) {
	var perr *workspace.PolicyError
	if errors.As(err, &perr) {
		payload, mErr := json.Marshal(map[string]any{"violations": perr.Violations})
		if mErr == nil {
			_ = store.AddEventWithPayload(ctx, taskID, "policy_violation", perr.Error(), payload)
			return
		}
	}
	_ = store.AddEvent(ctx, taskID, "policy_violation", err.Error())
}

func createPR(ctx context.Context, t task.Task, cfg workflow.Config) error {
	client := gitea.Client{BaseURL: os.Getenv("GITEA_BASE_URL"), Token: os.Getenv("GITEA_TOKEN")}
	body := fmt.Sprintf("## AI Task\n\nTask ID: `%s`\n\n## Source\n\n%s / %s\n\n## Changes\n\nGenerated by aiops-platform Symphony-style worker.\n\n## Verification\n\nSee workflow verify commands and worker logs.\n\n## Risk\n\nHuman review required.\n", t.ID, t.SourceType, t.SourceEventID)
	pr, err := client.CreatePullRequest(ctx, gitea.CreatePullRequestInput{Owner: t.RepoOwner, Repo: t.RepoName, Title: "chore(ai): " + t.Title, Body: body, Head: t.WorkBranch, Base: t.BaseBranch})
	if err != nil {
		return err
	}
	log.Printf("task %s created PR #%d %s", t.ID, pr.Number, pr.HTMLURL)
	return nil
}

func writeTaskFiles(workdir string, t task.Task, prompt string) error {
	if err := workspace.WritePrompt(workdir, prompt); err != nil {
		return err
	}
	return os.WriteFile(workdir+"/.aiops/TASK.md", []byte(fmt.Sprintf("# Task %s\n\n%s\n", t.ID, t.Description)), 0o644)
}

func env(k, d string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return d
}
