package runner

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// MockRunner is the Symphony-style Day-1 runner used in tests and the
// `mock` agent path. Sleep, when > 0, makes the runner block until either
// it elapses or the context is cancelled — this is how tests drive the
// timeout path without spawning a real subprocess.
type MockRunner struct {
	Sleep time.Duration
}

func (m MockRunner) Run(ctx context.Context, in RunInput) (Result, error) {
	if err := m.awaitMockSleep(ctx); err != nil {
		return Result{}, err
	}

	dir := filepath.Join(in.Workdir, ".aiops")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return Result{}, err
	}
	completedAt := time.Now().Format(time.RFC3339)

	if err := m.writeMockTaskArtifact(dir, in, completedAt); err != nil {
		return Result{}, err
	}
	return Result{Summary: "mock completed"}, nil
}

// awaitMockSleep blocks for m.Sleep (when > 0) so tests can drive the timeout
// path. It returns a *TimeoutError when the context deadline elapsed and the
// bare ctx.Err() for any other cancellation (e.g. context.Canceled), matching
// the worker's timeout-vs-cancel retry routing. The timer is always stopped on
// every return path.
func (m MockRunner) awaitMockSleep(ctx context.Context) error {
	if m.Sleep <= 0 {
		return nil
	}
	start := time.Now()
	t := time.NewTimer(m.Sleep)
	defer t.Stop()
	select {
	case <-ctx.Done():
		elapsed := time.Since(start)
		if errors.Is(ctx.Err(), context.DeadlineExceeded) {
			return &TimeoutError{
				Timeout: deadlineBudget(ctx, start),
				Elapsed: elapsed,
				Cause:   ctx.Err(),
			}
		}
		return ctx.Err()
	case <-t.C:
		return nil
	}
}

// writeMockTaskArtifact writes the per-task .aiops/<task>.md file recording the
// task metadata the mock runner "completed".
func (m MockRunner) writeMockTaskArtifact(dir string, in RunInput, completedAt string) error {
	content := fmt.Sprintf(`# AI Ops Mock Run

Task: %s
Title: %s
Actor: %s
Model: %s
Completed at: %s

This file is generated by the Symphony-style Day 1 mock runner.

Prompt was written to .aiops/PROMPT.md.
`, in.Task.ID, in.Task.Title, in.Task.Actor, in.Task.Model, completedAt)
	if err := os.WriteFile(filepath.Join(dir, in.Task.ID+".md"), []byte(content), 0o644); err != nil {
		return err
	}
	return nil
}
