package runner

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// MockRunner is the Symphony-style Day-1 runner used in tests and the
// `mock` agent path. Sleep, when > 0, makes the runner block until either
// it elapses or the context is cancelled — this is how tests drive the
// timeout path without spawning a real subprocess.
type MockRunner struct {
	Sleep time.Duration
}

func (m MockRunner) Run(ctx context.Context, in RunInput) (Result, error) {
	if m.Sleep > 0 {
		start := time.Now()
		t := time.NewTimer(m.Sleep)
		defer t.Stop()
		select {
		case <-ctx.Done():
			elapsed := time.Since(start)
			if errors.Is(ctx.Err(), context.DeadlineExceeded) {
				return Result{}, &TimeoutError{
					Timeout: deadlineBudget(ctx, start),
					Elapsed: elapsed,
					Cause:   ctx.Err(),
				}
			}
			return Result{}, ctx.Err()
		case <-t.C:
		}
	}

	dir := filepath.Join(in.Workdir, ".aiops")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return Result{}, err
	}
	completedAt := time.Now().Format(time.RFC3339)
	content := fmt.Sprintf(`# AI Ops Mock Run

Task: %s
Title: %s
Actor: %s
Model: %s
Completed at: %s

This file is generated by the Symphony-style Day 1 mock runner.

Prompt was written to .aiops/PROMPT.md.
`, in.Task.ID, in.Task.Title, in.Task.Actor, in.Task.Model, completedAt)
	if err := os.WriteFile(filepath.Join(dir, in.Task.ID+".md"), []byte(content), 0o644); err != nil {
		return Result{}, err
	}
	// Write the RUN_SUMMARY.md artifact the worker requires before opening
	// a PR. The mock runner produces a minimal but recognisably non-stub
	// summary so the worker's CheckSummary gate accepts it.
	summary := fmt.Sprintf(`# Run summary (mock)

- Task: %s
- Title: %s
- Actor: %s
- Model: %s
- Completed at: %s

This summary was produced by the mock runner. The mock runner does not edit
source files; it writes only its own .aiops/<task>.md and this RUN_SUMMARY.md
so end-to-end gating logic (worker requires RUN_SUMMARY.md before opening a
PR) can be exercised in tests and local dev.
`, in.Task.ID, in.Task.Title, in.Task.Actor, in.Task.Model, completedAt)
	if err := os.WriteFile(filepath.Join(dir, "RUN_SUMMARY.md"), []byte(summary), 0o644); err != nil {
		return Result{}, fmt.Errorf("write RUN_SUMMARY.md: %w", err)
	}
	return Result{Summary: "mock completed"}, nil
}
