#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/enqueue-manual-task.sh

Required environment variables:
  REPO_OWNER     Repository owner or organization.
  REPO_NAME      Repository name.
  CLONE_URL      Git clone URL used by the worker.

Optional environment variables:
  AIOPS_API_URL      Trigger API base URL. Default: http://localhost:8080
  BASE_BRANCH        Base branch for the task branch. Default: main
  WORK_BRANCH        Worker branch name. Default: generated by trigger-api
  TITLE              Task title. Default: Manual smoke task
  DESCRIPTION        Task description. Default: Manual task submitted by this script
  ACTOR              Task actor. Default: current user
  MODEL              Runner model. Default: mock
  SOURCE_EVENT_ID    Idempotency key. Default: manual-<timestamp>-<pid>
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

require_env() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "Missing required environment variable: $name" >&2
    echo >&2
    usage >&2
    exit 2
  fi
}

json_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  value="${value//$'\r'/\\r}"
  value="${value//$'\t'/\\t}"
  printf '%s' "$value"
}

json_pair() {
  local name="$1"
  local value="$2"
  printf '"%s":"%s"' "$name" "$(json_escape "$value")"
}

require_env REPO_OWNER
require_env REPO_NAME
require_env CLONE_URL

api_url="${AIOPS_API_URL:-http://localhost:8080}"
base_branch="${BASE_BRANCH:-main}"
title="${TITLE:-Manual smoke task}"
description="${DESCRIPTION:-Manual task submitted by scripts/enqueue-manual-task.sh}"
actor="${ACTOR:-${USER:-manual}}"
model="${MODEL:-mock}"
source_event_id="${SOURCE_EVENT_ID:-manual-$(date +%s)-$$}"

pairs=(
  "$(json_pair source_type manual)"
  "$(json_pair source_event_id "$source_event_id")"
  "$(json_pair repo_owner "$REPO_OWNER")"
  "$(json_pair repo_name "$REPO_NAME")"
  "$(json_pair clone_url "$CLONE_URL")"
  "$(json_pair base_branch "$base_branch")"
  "$(json_pair title "$title")"
  "$(json_pair description "$description")"
  "$(json_pair actor "$actor")"
  "$(json_pair model "$model")"
)

if [[ -n "${WORK_BRANCH:-}" ]]; then
  pairs+=("$(json_pair work_branch "$WORK_BRANCH")")
fi

payload="$(IFS=,; printf '{%s}\n' "${pairs[*]}")"
payload_file="$(mktemp)"
trap 'rm -f "$payload_file"' EXIT
printf '%s' "$payload" >"$payload_file"

response="$(
  curl -fsS \
    -X POST \
    -H 'Content-Type: application/json' \
    --data-binary "@$payload_file" \
    "${api_url%/}/v1/tasks"
)"

task_id="$(printf '%s' "$response" | sed -n 's/.*"task_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"
if [[ -z "$task_id" ]]; then
  echo "Task was submitted, but response did not include task_id:" >&2
  printf '%s\n' "$response" >&2
  exit 1
fi

echo "Task enqueued: $task_id"
echo "Response: $response"
echo
echo "Next verification command:"
printf '%s\n' "docker compose --env-file .env -f deploy/docker-compose.yml exec postgres psql -U aiops -d aiops -c \"select id,status,repo_owner,repo_name,work_branch,updated_at from tasks where id='$task_id';\""
